chore: update npm packages to outdated wanted versions

diff --git a/.lighthouse/jenkins-x/pullrequest.yaml b/.lighthouse/jenkins-x/pullrequest.yaml
--- a/.lighthouse/jenkins-x/pullrequest.yaml
+++ b/.lighthouse/jenkins-x/pullrequest.yaml
@@ -269,21 +269,21 @@ spec:
           command:
           - /bin/sh
           - -c
-          image: dockeronce.azurecr.io/cloudbees/nodejs:sonf-v22.14.0
+          image: dockeronce.azurecr.io/cloudbees/nodejs:sonf-v22.16.0
           name: install-packages
         - args:
           - npm run prettier
           command:
           - /bin/sh
           - -c
-          image: dockeronce.azurecr.io/cloudbees/nodejs:sonf-v22.14.0
+          image: dockeronce.azurecr.io/cloudbees/nodejs:sonf-v22.16.0
           name: check-prettier
         - args:
           - npm run lint
           command:
           - /bin/sh
           - -c
-          image: dockeronce.azurecr.io/cloudbees/nodejs:sonf-v22.14.0
+          image: dockeronce.azurecr.io/cloudbees/nodejs:sonf-v22.16.0
           name: check-lint
         - args:
           - export NODE_ENV="test" && npm run test
@@ -300,6 +300,51 @@ spec:
           - -c
           image: gcr.io/kaniko-project/executor:v1.9.1-debug
           name: docker-build
+          resources: {}
+        - args:
+          - |
+            set -e
+            echo "Scanning image $DOCKER_REGISTRY/$REPO_NAME:$(cat VERSION)-PR-${PULL_NUMBER} with Trivy..."
+            trivy image --exit-code 0 $DOCKER_REGISTRY/$REPO_NAME:$(cat VERSION)-PR-${PULL_NUMBER}
+            scan_exit_code=$?
+            if [ $scan_exit_code -ne 0 ]; then
+              echo "Trivy scan failed. Exiting."
+              exit 1
+            fi
+            echo "Trivy scan completed successfully."
+          command:
+          - /bin/sh
+          - -c
+          image: dockeronce.azurecr.io/trivy:latest
+          name: trivy-scan
+          env:
+          - name: AZURE_CLIENT_ID
+            valueFrom:
+              secretKeyRef:
+                name: trivy-sp
+                key: AZURE_CLIENT_ID
+          - name: AZURE_CLIENT_SECRET
+            valueFrom:
+              secretKeyRef:
+                name: trivy-sp
+                key: AZURE_CLIENT_SECRET
+          - name: AZURE_TENANT_ID
+            valueFrom:
+              secretKeyRef:
+                name: trivy-sp
+                key: AZURE_TENANT_ID
+          - name: TRIVY_USERNAME
+            valueFrom:
+              secretKeyRef:
+                name: trivy-sp
+                key: AZURE_CLIENT_ID
+          - name: TRIVY_PASSWORD
+            valueFrom:
+              secretKeyRef:
+                name: trivy-sp
+                key: AZURE_CLIENT_SECRET
+          - name: TRIVY_AUTH_URL
+            value: https://login.microsoftonline.com/$(AZURE_TENANT_ID)/oauth2/token
           resources: {}
         volumes:
         - emptyDir: {}
